[VIR-199] 리액션 기능 추가
SWM-Codection/gitea pull request #106
Opened 2024-10-02 11:06 UTC by cloudchamb3r

ReactionList 의 경우 discussion_client 로 위치가 변경되었습니다

2024-10-03 06:18 UTC, Lieslot requested changes

2024-10-03 06:18 UTC, Lieslot commented on client/discussion/discussion_client.go
> +	return result, err
이 부분 에러 처리가 안된 거 같습니당

2024-10-03 06:18 UTC, Lieslot commented on routers/web/repo/discussion.go
> +	}
이 부분은 관련 변수들이 어차피 다 DiscussionReactionRequest에 묶여있어서 구조체 메소드로 빼는 게 좋지 않나 싶습니당.

2024-10-03 06:19 UTC, cloudchamb3r commented on client/discussion/discussion_client.go
> +	return result, err
그러네요

2024-10-03 06:20 UTC, cloudchamb3r commented on routers/web/repo/discussion.go
> +	}
gitea 구현을 따랐습니다

2024-10-03 17:03 UTC, sangcheol12 approved these changes

2024-10-04 01:27 UTC, Lieslot approved these changes

2024-10-04 01:28 UTC, merged