PR AI 정적 분석 기능 API 구현
SWM-Codection/gitea pull request #24
Opened 2024-08-01 03:03 UTC by Lieslot

#15 해결 

주석 부분은 따로 기록해두느라 추가한 거라서 무시해도 OK

2024-08-01 04:49 UTC, cloudchamb3r requested changes
답글 단 사항 이외에도, 대체적으로 추가한 주석들이 있었습니다. 주석들로 표현하는것도 물론 좋지만, Github Discussion 에 알려야할 내용이 있다면, 정리해서 알려주는것도 상당히 좋을것으로 판단됩니다!

2024-08-01 04:49 UTC, cloudchamb3r commented on services/uinotification/notify_discussion.go
사실상 아무 역할도 하지 않는 파일인데 추가한 이유가 있을까요?

2024-08-01 04:49 UTC, cloudchamb3r commented on services/ai/review.go
> +var apiURL = "http://localhost:8000/api/pulls"
하드 코딩하신 이유가 있을까요? 
app.ini setting에 추가하시는걸 오히려 추천합니다 
#25 를 참고해보세요

2024-08-01 04:49 UTC, cloudchamb3r commented on services/ai/review.go
> +				return
왜 여기서는 err 를 던지지 않을까요

2024-08-01 04:49 UTC, cloudchamb3r commented on services/ai/review.go
> +func (aiController *AiServiceImpl) CreateAiPullComment(ctx *context.Context, form *api.CreateAiPullCommentForm, aiRequester AiRequester, adapter DbAdapter) error {
(bool, error) 타입으로 성공여부를 명시를 한다던가 하는 대처는 어떨까요? 물론 error를 반환하는 순간 필요가 없을수도 있다는 생각도 있습니다 ㅋㅋ..

2024-08-01 04:49 UTC, cloudchamb3r commented on services/uinotification/discussion.go
필요없는 파일입니다. 혹시 추가하신 이유가 있을까요?

2024-08-01 04:49 UTC, cloudchamb3r commented on routers/web/repo/ai_review.go
필요 없는 파일입니다. 단 주석 친데에는 이유가 있을거라고 생각합니다. 이유를 알려주실수 있을까요?

2024-08-01 04:50 UTC, cloudchamb3r commented on services/ai/review.go
> +func (aiController *AiServiceImpl) CreateAiPullComment(ctx *context.Context, form *api.CreateAiPullCommentForm, aiRequester AiRequester, adapter DbAdapter) error {
이부분에서는, 지금와서 드는 생각은 그냥 error만 던져도 문제가 없겠다 싶습니다!

2024-08-01 04:53 UTC, Lieslot commented on services/ai/review.go
> +var apiURL = "http://localhost:8000/api/pulls"
당장 의존성 주입을 어떻게 하면 좋을지 좋은 방법이 생각이 안나서 임시방편으로 하드코딩 했습니당. 첨 알았는데 이런 식으로도 의존성 주입이 가능하겠네요. 감사합니다!

2024-08-01 05:02 UTC, Lieslot commented on services/ai/review.go
> +				return
goroutine 내부에서 에러를 반환할 필요가 없을 거 같아서 그랬습니다. 생각해보니 여기에 재시도 로직 같은 걸 넣어야 될 것 같고, 재시도를 해도 생성이 안된 경우 추후에 별개의 파일 별로 정적 리뷰 요청을 다시 하게 만들지 말지도 생각해봐야 겠습니다.

2024-08-01 05:02 UTC, Lieslot commented on services/uinotification/discussion.go
아아 안그래도 삭제하려고 했었는데 까먹었었네요. 지적 감사합니다!

2024-08-01 05:05 UTC, cloudchamb3r commented on services/ai/review.go
> +				return
사실 에러를 먹을수도 있긴합니다. 단, 아무런 말도 없이 에러를 먹어버린다면 추후 문제가 생겼을때 판단하기 상당히 곤란할 수 있습니다. 가능하다면 로그등을 통해서 이러한 에러들이 있었다 정도만 명시해주셔도 문제는 없을것 같습니다.

2024-08-01 05:06 UTC, Lieslot commented on services/ai/review.go
> +				return
어떤 에러가 발생했는지에 대한 메세지는 출력하도록 수정할게요!

2024-08-02 01:41 UTC, cloudchamb3r approved these changes
LGTM

2024-08-02 01:41 UTC, cloudchamb3r commented on services/ai/review.go
> +	requestBytes, _ := json.Marshal(request)
이부분엔 resty 한번 도입해보시는것도 추천해요

2024-08-02 01:41 UTC, merged