Feature/vir 138 discussion ai sample code api
SWM-Codection/gitea pull request #31
Opened 2024-08-05 08:37 UTC by Lieslot

2024-08-05 09:13 UTC, cloudchamb3r requested changes
굿굿 조금만 바꿔주세요

2024-08-05 09:13 UTC, cloudchamb3r commented on services/ai/review.go
> +	response, err := client.Request().SetBody(request).Post(fmt.Sprintf(apiURL + "/api/sample"))
apiUrl + "path" 
이런식으로 진행하는것보다 차라리 gitea/client/ai 를 따로 만드시는게 좋을거같아요

2024-08-05 09:13 UTC, cloudchamb3r commented on services/ai/discussion.go
> +	sampleCodes := make([]*AiSampleCodeResponse, 0, 3)
AI_SAMPLE_CODE_UNIT
requestCnt
3
사실상 모두 같은 역할이고, 변하는 값들도 아닙니다.. 이런 값들이 많아지면 심각하게 유지보수가 어려워 질 수 있습니다

2024-08-05 13:54 UTC, sangcheol12 reviewed
수고하셨어요

2024-08-06 06:57 UTC, Lieslot commented
> 굿굿 조금만 바꿔주세요

반영했습니다.

2024-08-06 06:58 UTC, cloudchamb3r requested changes

2024-08-06 06:58 UTC, cloudchamb3r commented on services/ai/.cph/.discussion.go_949aadca79211398980b2cfc8bb0da40.prob
이 파일은 왜 추가됐나요?

2024-08-06 06:59 UTC, Lieslot commented on services/ai/discussion.go
> +	}
다른 함수로 빼려다 보니 인자가 5, 6개로 늘어나 버려서 일단 그대로 갔습니다.

2024-08-06 06:59 UTC, cloudchamb3r commented on services/ai/.cph/.discussion.go_949aadca79211398980b2cfc8bb0da40.prob
더미 파일 같은데, 제거 하고 다시 올려주세요!

2024-08-06 07:01 UTC, Lieslot commented on services/ai/.cph/.discussion.go_949aadca79211398980b2cfc8bb0da40.prob
넵 제거했씁니당

2024-08-06 07:02 UTC, cloudchamb3r approved these changes
LGTM

2024-08-06 07:39 UTC, merged